### ISSUE TITLE
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by xehyn** [rubenespadas/DionaeaFR#27]
Hi, 
Running sudo python manage.py collectstatic produces this error:

_  File "/usr/local/lib/python2.7/dist-packages/django_tables2/utils.py", line 109, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'_

I use Ubuntu 14.04, Django 1.9 (tested 1.48 and the same problem), six 1.10.

**Comment by EEEden** [comment]
I had the same problem and fixed it by upgrading six. Apparently that decorator was introduced in six 1.9.0 which I downloaded and installed from here:

https://pypi.python.org/pypi/six/1.9.0

**Comment by davidswelt** [comment]
thank you, EEEden, for pointing this out.  This fixed the issue for me as well.

**Comment by xehyn** [comment]
Thank you, my problem was solved six upgrade to the latest version of the library. I moved on.

**Comment by deepPython** [comment]
I am facing the same issue while running django server. I am not using virtual environment. Also, six package is on latest version in python. But still getting the error, What am I doing wrong?

pip show six

Name: six
Version: 1.10.0
Location: /usr/local/lib/python2.7/dist-packages
Requires

$python ~/django/mysite/manage.py runserver localhost
[1] 3913
$ AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
